### PR TITLE
Added support for read_xport

### PR DESCRIPTION
**Pull request by cipherz**
- C_interface.jl:
   Changed return type for readstat_get_row_count to Int (from UInt), as it seems that not all format contains nrows as metainformation and -1 is returned in those instances (xport is one of such formats).
   Added readstat_parse for type::Val{:xport}, calls readstat_parse_xport.

 - ReadStat.jl:
   Added constant READSTAT_NALLOC_ROWS: number of rows to allocate at the same time (see handle_variable! and handle_value!)
   Added read_xport and exported it.
   Modified read_data_file, handle_variable! and handle_value! to support formats without nrows metainformation.

- Test
  Added test cases for xpt and types.xpt.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Cool, thanks!

I was not aware that `readstat_get_row_count` can return `-1`, that seems important to handle, thanks for spotting that! I'm wondering, though, whether we should handle that case differently. I think in that case I would just allocate vectors with 0 elements, and then `push!` into those. I think the algorithm in `push!` is better at growing arrays than using a fixed increment like `READSTAT_NALLOC_ROWS`.

I'll try to fix the CI failures on `master`, and then you can merge `master` back into this branch and we'll hopefully get CI tests passing.

**Comment by davidanthoff** [comment]
Alrigh, #51 fixed the CI builds on `master`. So if you merge `master` into your branch, you should have a baseline that passes CI builds.

**Comment by cipherz** [comment]
I did not realize that push! would grow as needed, just started out with
Julia recently. I am also wondering if it is worth splitting up the code a
bit more and formats with nrows in the header, like the ones originally
implemented, would retain the original implementation, the fastest, and the
auto-growing (via push!) would only be used for formats without row count
information. Being a bit of a novice, I am tempted to take the approach to
making it type based used in other parts of the code, but I don't know if
there is a better way.

I will merge the new master into my branch and make some proposed changes
to address the points above.

**Comment by davidanthoff** [comment]
Yes, I think having a different code path for the case with known size and the case without would be good, we don't want to use `push!` if we know the size beforehand!

**Comment by vjd** [comment]
Just following up here to see if there are plans to support `xpt` files?

**Comment by davidanthoff** [comment]
I believe this is fully covered by #75, so closing this here.

**Pull request closed without merging**
